export const DEBUG = false; // draw the debug line so we can see what it's doing, helps if you turn off the blur filter, too
export const CURVE_POINTS = 10; // curve control points, not counting vanishingPoint
export const CURVE_POINT_X_JITTER = 1.1; // how far off the base location a point can go, in percentage of difference from previous point
export const CURVE_POINT_Y_JITTER = 3.5;
export const CURVE_POINT_MAX_FLOAT_X_DIST = 170; // 270 // farthest a curve point can float per keyframe
export const CURVE_POINT_MAX_FLOAT_Y_DIST = 80; // 80
export const CURVE_POINT_MIN_FLOAT_DIST = 15; // 15
export const CURVE_POINT_MAX_FLOAT_TIME = 8000; // longest a curve point can take to get to next keyframe
export const CURVE_POINT_MIN_FLOAT_TIME = 4000; // shortest a curve point can take to get to next keyframe
export const BRUSH_COUNT = 1000;
export const BRUSH_WIDTH = 5; // 30
export const BRUSH_HEIGHT = 450; // 450
export const BRUSH_MIN_SCALE_Y = 0.02;
export const BRUSH_MAX_SCALE_Y_VARIANCE = 0.5; // 0.5
export const BRUSH_MAX_ALPHA_VARIANCE = 0.7;
export const BRUSH_MAX_ANIM_TIME = 7000;
export const BRUSH_MIN_ANIM_TIME = 1500;
export const BRUSH_MAX_Z_ANIM_TIME = 100000; // 80000
export const BRUSH_MIN_Z_ANIM_TIME = 18000; // 58000
export const BRUSH_ALPHA_DROPOFF = 0.07;
export const MOUSE_X_OFFSET = 50;
export const MOUSE_Y_OFFSET = 25;
