name: "API services"
on:
  push:
    branches:
      - master
    paths:
      - "packages/services/api/**"
jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
  build:
    name: "Build"
    needs: test
    runs-on: ubuntu-latest
